//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF1_Online_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Championship
    {
        public string Unique_Key { get; set; }
        public string Name { get; set; }
        public string Rules_Description { get; set; }
        public System.DateTime Beginning_Date { get; set; }
        public System.TimeSpan Beginning_Time { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public System.TimeSpan Ending_Time { get; set; }
        public string Public_League_Name { get; set; }
        public bool CurrentChamp { get; set; }
    }
}
