//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF1_Online_REST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XF1OnlineEntities : DbContext
    {
        public XF1OnlineEntities()
            : base("name=XF1OnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Championship> Championships { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
