//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF1_Online_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public string Name { get; set; }
        public string Racing_Team { get; set; }
        public decimal Price { get; set; }
        public string Photo { get; set; }
    }
}
