//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF1_Online_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public string Name { get; set; }
        public string Champ_Key { get; set; }
        public string Country { get; set; }
        public string Status { get; set; }
        public System.DateTime Qualification_Date { get; set; }
        public System.DateTime Competition_Date { get; set; }
        public string Track_Name { get; set; }
        public System.DateTime Beginning_Date { get; set; }
        public System.TimeSpan Beginning_Time { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public System.TimeSpan Ending_Time { get; set; }
    
        public virtual Championship Championship { get; set; }
    }
}
